
all:
	gcc -Wall -Wextra generator.c -I ../../inc/ -I ../../libft/includes -L ../../libft -lft -o random_input_generator
print_all_shapes:
	gcc -Wall -Wextra print_all_shapes.c -I ../../inc/ -I ../../libft/includes -L ../../libft -lft -o print_all_shapes
